
export { BsCheck2 as CheckIcon } from 'react-icons/bs' 
export { BsX as XIcon } from 'react-icons/bs'
export { BsExclamationTriangle as ExclamationIcon } from 'react-icons/bs'
export { BsExclamationCircle as ExclamationCircleIcon } from 'react-icons/bs'
export { BsEnvelopeAt as EmailIcon } from 'react-icons/bs'
export { BsGeoAlt as LocationIcon } from 'react-icons/bs'
export { BsPhone as PhoneIcon } from 'react-icons/bs'
export { BsLink45Deg as WebsiteIcon } from 'react-icons/bs'
export { BsSearch as SearchIcon } from 'react-icons/bs'
export { BsInfoCircle as InformationCircleIcon } from 'react-icons/bs'
